Fixed bug: stack overflow on null requests
When running an iterate to repeat a null-request:
RangeError: Maximum call stack size exceeded

From (thanks! heinob):
http://stackoverflow.com/questions/20936486/node-js-maximum-call-stack-size-exceeded

"null" requests were recently added to allow scripts to specify and
process actions without sending an actual request. Because there was
no yield for the request, the tight loop didn't allow node.js to execute
cleanup.